all: code bankSim

# If you want to test your code outside of the unit
# tests, create a new .cpp file and add a main() function
#
bankSim:
	g++ -std=c++11 -o bankSim bankSim.cpp


code:
	g++ -std=c++11 -o code code.cpp

clean:
	rm code bankSim
